INSERT INTO Alumni (nama, angkatan, divisi, pekerjaan, perusahaan, kesan_pesan, tahun_lulus, keahlian, linkedin, portfolio, email, foto) VALUES
('Rizwan Alfian', 2023, 'Koordinator Lab', 'Software Engineer', 'Tokopedia', 'Pengalaman yang luar biasa menjadi asisten di lab ini. Banyak ilmu yang saya dapatkan terutama dalam teamwork dan kepemimpinan.', 2023, 'PHP, Laravel, React, MySQL, Docker', 'https://linkedin.com/in/rizwan', 'https://rizwan.dev', 'rizwan@email.com', 'https://placehold.co/300x300/667eea/white?text=Rizwan'),
('Siti Nurhaliza', 2023, 'Divisi Jaringan', 'Network Engineer', 'Telkom Indonesia', 'Awal yang baik untuk karir di dunia telekomunikasi. Terima kasih atas bimbingan selama menjadi asisten.', 2023, 'Cisco, Networking, Linux', 'https://linkedin.com/in/siti-nurhaliza', 'https://siti-portfolio.com', 'siti@email.com', 'https://placehold.co/300x300/667eea/white?text=Siti'),
('Ahmad Pratama', 2022, 'Divisi Multimedia', 'UI/UX Designer', 'Gojek', 'Laboratorium membentuk kreativitas saya dan membuat saya percaya bahwa desain itu penting.', 2022, 'Figma, Adobe XD, UI/UX Design, Web Design', 'https://linkedin.com/in/ahmad-pratama', 'https://ahmad-design.com', 'ahmad@email.com', 'https://placehold.co/300x300/667eea/white?text=Ahmad'),
('Dwi Putri Lestari', 2022, 'Koordinator Lab', 'ASN Kominfo', 'Kementerian Komunikasi dan Informatika', 'Bangga bisa melayani negara dengan keahlian yang didapat dari laboratorium. Semoga lab terus berkembang.', 2022, 'Public Policy, IT Governance, Java', 'https://linkedin.com/in/dwi-putri', 'https://dwi-portfolio.com', 'dwi@email.com', 'https://placehold.co/300x300/667eea/white?text=Dwi'),
('Budi Santoso', 2021, 'Divisi Database', 'Data Analyst', 'Bukalapak', 'Belajar banyak tentang data dan database management. Menjadi asisten adalah keputusan terbaik saya.', 2021, 'SQL, Python, Data Analysis, PostgreSQL', 'https://linkedin.com/in/budi-santoso', 'https://budi-analytics.com', 'budi@email.com', 'https://placehold.co/300x300/667eea/white?text=Budi'),
('Eka Sulistyaningrum', 2021, 'Divisi Web', 'Frontend Developer', 'Shopee', 'Pengalaman di lab mengajarkan saya tentang deadline management dan code quality yang baik.', 2021, 'JavaScript, React, Vue, HTML/CSS', 'https://linkedin.com/in/eka-sulistya', 'https://eka-frontend.com', 'eka@email.com', 'https://placehold.co/300x300/667eea/white?text=Eka'),
('Fajar Wijaya', 2020, 'Divisi Sistem', 'DevOps Engineer', 'Jago.com', 'Infrastruktur yang kami bangun di lab menjadi fondasi pengetahuan saya tentang system administration.', 2020, 'AWS, Docker, Kubernetes, Linux', 'https://linkedin.com/in/fajar-wijaya', 'https://fajar-devops.com', 'fajar@email.com', 'https://placehold.co/300x300/667eea/white?text=Fajar'),
('Hani Khoirunisa', 2020, 'Divisi Multimedia', 'Motion Graphics Designer', 'Trans Media', 'Lab memberikan saya portofolio yang solid untuk masuk ke industri kreatif.', 2020, 'After Effects, Premiere Pro, Animation, UI Design', 'https://linkedin.com/in/hani-khoirunisa', 'https://hani-motion.com', 'hani@email.com', 'https://placehold.co/300x300/667eea/white?text=Hani');
